### ISSUE TITLE
WSS protocol not working

### ISSUE THREAD

**Issue by pluzmedia** [Vovaman/example_async_websocket#5]
Hi,

When it try to connect wss protocol it gives me `Exception: 'NoneType' object has no attribute 'host'`. WSS implementation would be good in terms of security. Any help would be appreciated. Thanks

**Comment by pluzmedia** [comment]
I made it to work by editing ws.py file
`URL_RE = re.compile(r'ws://([A-Za-z0-9\-\.]+)(?:\:([0-9]+))?(/.+)?')`
to
`URL_RE = re.compile(r'wss://([A-Za-z0-9\-\.]+)(?:\:([0-9]+))?(/.+)?')`

**Comment by Vovaman** [comment]
So, bettter place for this issue is 'https://github.com/Vovaman/micropython_async_websocket_client'.
It is not enough to change 'ws' to 'wss' for security. 
1) It is preferable to keep both modes: secure and not secure
2) correct implementation for security includes work with certificates and it adds additional load for controller
And this is why I've planned realize it later.

**Comment by pluzmedia** [comment]
Thanks

**Comment by Vovaman** [comment]
I'll rebase this issue to https://github.com/Vovaman/micropython_async_websocket_client and will include it to next release.

**Comment by Vovaman** [comment]
@pluzmedia , you know, I think again and it's really makes sense to realize wss as a first step to normal security. thanx for idea.
will make it in a days.

**Comment by pluzmedia** [comment]
@Vovaman it's great

**Comment by pluzmedia** [comment]
@Vovaman Do consider to pass custom headers during handshake. I did following to pass custom header

`headers = [["device_id", 1]]`
`ws.handshake("wss://host:port", headers)`

in ws.py
```
async def handshake(self, uri, headers):
for key, value in headers:
            print(key)
            print(value)
            send_header(b'%s: %s', key, value)
```

**Comment by Vovaman** [comment]
Ok. It is also reasonable.
But: 
1) Headers is another functionality vs wss. Thus it has to be another issue.
2) Let's create new issue in  https://github.com/Vovaman/micropython_async_websocket_client, because this project is just example of using that package.
3) would you, please, explain, what info you send in headers. It is important due to we have to extremely minimize functionality on controller.

**Comment by pluzmedia** [comment]
@Vovaman need to send header value like api key to authenticate during handshake also I have implemented ssl wrapper. If you like It I am ready to make a pull request.

**Comment by Vovaman** [comment]
Ok.

**Comment by manix** [comment]
is `wss` implemented?

**Comment by Vovaman** [comment]
Not yet. Will make it till end of august.

**Comment by manix** [comment]
Well, [here](https://github.com/danni/uwebsockets) it seems to be supported, and messages get loaded much faster, but is not async.

You can check it out if it helps in development.
